/*
  # Add server-side token to game_sessions

  1. Changes
    - Add `token` column to game_sessions table
    - This is a server-only secret that validates session authenticity
    - Generated by start-game edge function, verified by submit-score
    - Never exposed to the client

  2. Security
    - Prevents session forgery even if session_id is known
    - Token is a random string generated server-side
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'game_sessions' AND column_name = 'token'
  ) THEN
    ALTER TABLE game_sessions ADD COLUMN token text NOT NULL DEFAULT '';
  END IF;
END $$;